version: "3.9"
services:
  download-tiles:
    image: alpine:latest
    volumes:
      - ./data:/data
    command:
      ash -c "cd /data && wget https://aktionskarten.github.io/tileserver-gl-data/tiles.mbtiles"
  clone-osm-bright:
    image: alpine/git:latest
    volumes:
      - ./data:/data
    command: 
      "clone https://github.com/aktionskarten/osm-bright-gl-style.git /data/osm-bright"
  tileserver-gl:
    image: kombinat451/tileserver-gl
    depends_on:
      - download-tiles
      - clone-osm-bright
    ports:
      - "127.0.0.1:1312:80"
    volumes:
      - ./data:/data
  postgis:
    image: postgis/postgis:13-3.1-alpine
    env_file:
      - ./postgis.env
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  backend:
    depends_on:
      - postgis
      - redis
      - tileserver-gl
    image: kombinat451/aktionskarten-backend-app
    ports:
      - 127.0.0.1:5000:5000
    environment:
      - POSTGRES_HOST=postgis
      - REDIS_HOST=redis
      - TILESERVER_HOST=tileserver-gl
    env_file:
      - "./postgis.env"
      - "./backend.env"
  aktionskartenJs:
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html
    ports: 
      - 127.0.0.1:8080:80
  tests:
    build: .
    user: pptruser
    cap_add:
      - SYS_ADMIN
    depends_on:
      - backend
      - aktionskartenJs
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
      - AKTIONSKARTEN_JS_HOST=aktionskartenJs
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - ./docker-test-entrypoint.sh:/usr/bin/docker-test-entrypoint.sh
    command: docker-test-entrypoint.sh
