name: github-actions
on: [push]
jobs: 
  test:
    runs-on: ubuntu-latest
    env:
      DOCKER_COMPOSE_VERSION: 2.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mbtiles
        run: wget https://aktionskarten.github.io/tileserver-gl-data/tiles.mbtiles
      - name: Start containers
        run: docker-compose up -d --build
      - name: Show currend docker-compose version
        run: docker-compose --version
      - name: Delete docker-compose
        run: sudo rm /usr/local/bin/docker-compose
      - name: Download docker-compose
        run: curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
      - name: Make docker-compose executable
        run: chmod +x docker-compose
      - name: Move docker compose to correct location
        run: sudo mv docker-compose /usr/local/bin
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 11
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Run http-server
        run: npx http-server dist &
      - name: Docker compose logs
        run: docker-compose logs
      - name: Wait for backend
        run: bash -c 'while ! wget -q -t 1 http://localhost:5000/api/maps; do echo waiting; sleep 1; done;'
      - name: Run tests
        run: npm run test
      - name: Stop containers
        run: docker-compose down
      - name: Stop http-server
        run: pkill -f http-server

