name: github-actions
on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379
      postgis:
        image: postgis/postgis:13-3.1-alpine
        ports:
          - 5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: maps

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download mbtiles
        run: wget https://aktionskarten.github.io/tileserver-gl-data/tiles.mbtiles
      - name: Start containers
        run: docker-compose up -d --build
      - name: Show docker containers
        run: docker ps -a
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 11
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Run http-server
        run: npx http-server dist &
      - name: Docker compose logs
        run: docker-compose logs
      - name: Wait for backend
        run: bash -c 'while ! wget -q -t 1 http://backend:5000/api/maps; do echo waiting; sleep 1; done;'
      - name: Run tests
        run: npm run test
      - name: Stop containers
        run: docker-compose down
      - name: Stop http-server
        run: pkill -f http-server

