name: tests and publish docker container

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo and subrepos
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Install node dependencies
        run: npm install
      -
        name: Build
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Run tests
        run: npm run tests

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - 
        name: Publish to npmjs.com
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
