name: tests and publish docker container

on:
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo and subrepos
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Install node dependencies
        run: npm install
      -
        name: Cache
        uses: actions/cache@v2
        id:setup 
        with:
          path: ./*

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Restore cache
        uses: actions/cache@v2
        id: setup 
        with:
          path: ./*
          key: ${{ github.sha }}
      -
        name: Build
        run: npm run build
      -
        name: Cache
        uses: actions/cache@v2
        id: build
        with:
          path: ./*
          key: ${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Restore cache
        uses: actions/cache@v2
        id: setup 
        with:
          path: ./*
          key: ${{ github.sha }}
      -
        name: Run tests
        run: npm run tests

  publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      -
        name: Restore cache
        uses: actions/cache@v2
        id: build
        with:
          path: ./*
          key: ${{ github.sha }}
      - 
        name: Publish to npmjs.com
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
